### ISSUE TITLE
vue-codemod转换后缺少空格

### ISSUE THREAD

**Issue by wangsongc** [Alanscut/vue-codemod#1]
**Describe the bug**
vue-codemod转换后缺少空格
**To Reproduce**
npx vue-codemod src/layouts/components/VabAppMain -a
项目：https://github.com/wangsongc/vue-admin-beautiful.git

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40830929/124233521-7fe6f180-db45-11eb-9e14-6380a32e43f6.png)

**Environment (please complete the following information):**

**Additional context**

**Comment by Alanscut** [comment]
已修复，详情见 https://github.com/originjs/vue-codemod/pull/  #68
