### ISSUE TITLE
template转换后有多余的空行

### ISSUE THREAD

**Issue by wangsongc** [Alanscut/vue-codemod#10]
**Describe the bug**
template转换后有多余的空行

**To Reproduce**
```
<template>
  <router-view />
</template>
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40830929/124349087-f9531280-dc1f-11eb-8db7-271d67c3eb76.png)

**Environment (please complete the following information):**

**Additional context**

**Comment by Alanscut** [comment]
问题无法复线，可能已被修复。
