### ISSUE TITLE
安装的@bable/core中不包含@babel/eslint-parser，需要单独安装

### ISSUE THREAD

**Issue by wangsongc** [Alanscut/vue-codemod#13]
**Describe the bug**
安装的@bable/core中不包含@babel/eslint-parser，需要单独安装

**To Reproduce**
error: Parsing error: Cannot find module 'babel-eslint'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by Alanscut** [comment]
同 #12 ，eslint 相关配置现在不进行改动，保持原样
