### ISSUE TITLE
建议main.js里面在创建Vue实例时加上`const app =`

### ISSUE THREAD

**Issue by wangsongc** [Alanscut/vue-codemod#3]
**Describe the bug**
main.js里面要不要能不能在创建Vue实例时加上`const app =`, 这样就不用再手工去改了

**To Reproduce**
```
Vue.prototype.shareConfig = shareConfig;
Vue.createApp(App).use(IconSvg).use(i18n).use(router).use(store).mount('#app')

```

**Expected behavior**
```
```
const app = Vue.createApp(App).use(IconSvg).use(i18n).use(router).use(store).mount('#app')
app.prototype.shareConfig = shareConfig;

```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. iOS]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by Alanscut** [comment]
已实现，详情见：https://github.com/originjs/vue-codemod/pull/  #78 & #80
