### ISSUE TITLE
vue-codemod --help的Usage需要修改

### ISSUE THREAD

**Issue by wangsongc** [Alanscut/vue-codemod#5]
**Describe the bug**
vue-codemod --help的Usage需要修改

**To Reproduce**
`Usage: vue-codemod.js [file pattern]`

**Expected behavior**
供参考：
`Usage: vue-codemod [file path] [option]`

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by Alanscut** [comment]
已修复，详情见：https://github.com/originjs/vue-codemod/pull #69
