### ISSUE TITLE
vue-codemod -p的用法问题

### ISSUE THREAD

**Issue by wangsongc** [Alanscut/vue-codemod#6]
**Describe the bug**
需要确认`-p`的用法，有没有必要暴露给用户

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40830929/124347444-78901880-dc17-11eb-89ad-f8ad35ad3ac4.png)

**Environment (please complete the following information):**

**Additional context**

**Comment by Alanscut** [comment]
跑单条规则的时候，部分规则是需要传入参数的，比如 remove-vue-use 需要传入需要删除的库
