### ISSUE TITLE
不应该将多行配置转换成一行

### ISSUE THREAD

**Issue by wangsongc** [Alanscut/vue-codemod#9]
**Describe the bug**
不应该将多行配置转换成一行，是否可以调用Prettier美化一下代码

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40830929/124348317-e2aabc80-dc1b-11eb-9ce6-762fb6914216.png)
![image](https://user-images.githubusercontent.com/40830929/124348345-fa824080-dc1b-11eb-9dcd-8272a4f9eaec.png)

**Environment (please complete the following information):**

**Additional context**

**Comment by Alanscut** [comment]
package.json 的处理已经使用第三方库 `fs-extra` 重新处理，会保留原始格式，不会压缩成一行。详情见：
已修复，详情见：https://github.com/originjs/vue-codemod/pull #77
